# Generated by Django 4.1 on 2023-02-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("message", models.TextField(null=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "date_de_publication_email",
                    models.DateField(
                        default="2023-11-10",
                        verbose_name="date de publication de la categorie ",
                    ),
                ),
            ],
            options={"verbose_name": "Message mail envoyé",},
        ),
        migrations.CreateModel(
            name="Subscribers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_subscriber", models.EmailField(max_length=254, unique=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "Subscriber",},
        ),
    ]
